pipeline:

  test:
    image: betch/godnd:1.18
    commands:
      - apt update
      - apt install -y build-essential libolm-dev sqlite3
      - go mod download
      - go build -o trix
      - DEBUG=false go test -v
    when:
      event: pull_request

  main:
    image: betch/godnd:1.18
    commands:
      - apt update
      - apt install -y build-essential libolm-dev sqlite3
      - go mod download
      - go build -o trix
      - DEBUG=false go test -v
    when:
      event: push
      branch: main

  mirror:
    image: betch/godnd:1.18
    secrets: [ github_user, github_pass ]
    commands:
      - mkdir github_mirror
      - cd github_mirror
      - git clone --bare https://codeberg.org/meh/trix.git
      - cd trix.git
      - git push --mirror https://$${GITHUB_USER}:$${GITHUB_PASS}@github.com/$${GITHUB_USER}/trix.git
    when:
      event: push
      branch: main

services:
  trix.meh:
    image: betch/trixtest:latest
