workspace:
  base: /src
  path: codeberg.org/meh/trix

pipeline:

  build:
    group: test
    image: betch/godnd:1.20
    commands:
      - apt update
      - apt install -y git build-essential libolm-dev sqlite3
      - go mod download
      - go build -ldflags "-X codeberg.org/meh/trix/cmd.version=$(git describe --tags $(git rev-list --tags --max-count=1) | sed 's/v//')" -o trix
      - DEBUG=false go test -v

  sec:
    group: test
    image: betch/godnd:1.20
    commands:
      - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b /bin
      - go get github.com/securego/gosec/v2/cmd/tlsconfig/...
      - go generate /src/codeberg.org/meh/trix/...
      - /bin/gosec /src/codeberg.org/meh/trix/...

  mirror:
    image: betch/godnd:1.20
    secrets: [github_user, github_pass]
    commands:
      - apt update
      - apt install -y git
      - mkdir github_mirror
      - cd github_mirror
      - git clone --bare https://codeberg.org/meh/trix.git
      - cd trix.git
      - git push --mirror https://$${GITHUB_USER}:$${GITHUB_PASS}@github.com/$${GITHUB_USER}/trix.git
    when:
      event: push
      branch: main

  release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: release_token
      base_url: https://codeberg.org
      files: trix
      file_exist: fail
      checksum: sha256
    when:
      event: tag
      tag: v*

services:
  trix.meh:
    image: betch/trixtest:latest
