VERSION 0.6
ARG VER

build:
  FROM golang:${VER}-bullseye
  WORKDIR /build
  RUN echo "deb http://deb.debian.org/debian bullseye-backports main contrib non-free" > /etc/apt/sources.list.d/bullseye-backports.list && \
    echo "deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free" >> /etc/apt/sources.list.d/bullseye-backports.list && \
    apt update && apt upgrade -y && apt install -y jq && \
    REL=$(curl -fsSL https://api.github.com/repos/earthly/earthly/releases/latest | jq -r '.tag_name') && \
    curl -o dockerd-install.sh -fsSL https://raw.githubusercontent.com/earthly/earthly/${REL}/buildkitd/docker-auto-install.sh && \
    chmod 755 dockerd-install.sh && ./dockerd-install.sh && apt -t bullseye-backports upgrade -y && cd /usr/local/go/src/cmd/ && go get -u ./...
  SAVE IMAGE --push docker.io/betch/godnd:${VER}

sec:
  FROM +build
  RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin && \
     curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
  WITH DOCKER --load docker.io/betch/godnd:${VER}=+build
    RUN grype db update && syft docker:betch/godnd:${VER} -o json=godnd.json && \
      grype sbom:./godnd.json --scope all-layers --add-cpes-if-none --distro debian:11 --only-fixed --fail-on critical
  END

ver18:
  BUILD +build --VER=1.18
  BUILD +sec --VER=1.18

ver19:
  BUILD +build --VER=1.19
  BUILD +sec --VER=1.19

ver20:
  BUILD +build --VER=1.20
  BUILD +sec --VER=1.20

all:
  BUILD +ver18
  BUILD +ver19
  BUILD +ver20
