# osv-scanner config.toml golang version 1.19
# i'm pretty certain the large number of vulns is because the official golang image is still on debian bullseye

[[IgnoredVulns]]
id = "GHSA-36xw-fx78-c5r4"
reason = "https://osv.dev/GHSA-36xw-fx78-c5r4"

[[IgnoredVulns]]
id = "GHSA-742w-89gc-8m9c"
reason = "https://osv.dev/GHSA-742w-89gc-8m9c"

[[IgnoredVulns]]
id = "GHSA-c72p-9xmj-rx3w"
reason = "https://osv.dev/GHSA-c72p-9xmj-rx3w"

[[IgnoredVulns]]
id = "GHSA-c2h3-6mxw-7mvq"
reason = "https://osv.dev/GHSA-c2h3-6mxw-7mvq"

[[IgnoredVulns]]
id = "GHSA-5j5w-g665-5m35"
reason = "https://osv.dev/GHSA-5j5w-g665-5m35"

[[IgnoredVulns]]
id = "GHSA-crp2-qrr5-8pq7"
reason = "https://osv.dev/GHSA-crp2-qrr5-8pq7"

[[IgnoredVulns]]
id = "GHSA-5ffw-gxpp-mxpf"
reason = "https://osv.dev/GHSA-5ffw-gxpp-mxpf"

[[IgnoredVulns]]
id = "GHSA-2qjp-425j-52j9"
reason = "https://osv.dev/GHSA-2qjp-425j-52j9"

[[IgnoredVulns]]
id = "GHSA-36xw-fx78-c5r4"
reason = "https://osv.dev/GHSA-36xw-fx78-c5r4"

[[IgnoredVulns]]
id = "GHSA-742w-89gc-8m9c"
reason = "https://osv.dev/GHSA-742w-89gc-8m9c"

[[IgnoredVulns]]
id = "GHSA-c72p-9xmj-rx3w"
reason = "https://osv.dev/GHSA-c72p-9xmj-rx3w"

[[IgnoredVulns]]
id = "GHSA-c2h3-6mxw-7mvq"
reason = "https://osv.dev/GHSA-c2h3-6mxw-7mvq"

[[IgnoredVulns]]
id = "GHSA-5j5w-g665-5m35"
reason = "https://osv.dev/GHSA-5j5w-g665-5m35"

[[IgnoredVulns]]
id = "GHSA-crp2-qrr5-8pq7"
reason = "https://osv.dev/GHSA-crp2-qrr5-8pq7"

[[IgnoredVulns]]
id = "GHSA-5ffw-gxpp-mxpf"
reason = "https://osv.dev/GHSA-5ffw-gxpp-mxpf"

[[IgnoredVulns]]
id = "GHSA-2qjp-425j-52j9"
reason = "https://osv.dev/GHSA-2qjp-425j-52j9"

[[IgnoredVulns]]
id = "GHSA-36xw-fx78-c5r4"
reason = "https://osv.dev/GHSA-36xw-fx78-c5r4"

[[IgnoredVulns]]
id = "GHSA-742w-89gc-8m9c"
reason = "https://osv.dev/GHSA-742w-89gc-8m9c"

[[IgnoredVulns]]
id = "GHSA-c72p-9xmj-rx3w"
reason = "https://osv.dev/GHSA-c72p-9xmj-rx3w"

[[IgnoredVulns]]
id = "GHSA-c2h3-6mxw-7mvq"
reason = "https://osv.dev/GHSA-c2h3-6mxw-7mvq"

[[IgnoredVulns]]
id = "GHSA-5j5w-g665-5m35"
reason = "https://osv.dev/GHSA-5j5w-g665-5m35"

[[IgnoredVulns]]
id = "GHSA-crp2-qrr5-8pq7"
reason = "https://osv.dev/GHSA-crp2-qrr5-8pq7"

[[IgnoredVulns]]
id = "GHSA-5ffw-gxpp-mxpf"
reason = "https://osv.dev/GHSA-5ffw-gxpp-mxpf"

[[IgnoredVulns]]
id = "GHSA-2qjp-425j-52j9"
reason = "https://osv.dev/GHSA-2qjp-425j-52j9"

[[IgnoredVulns]]
id = "GHSA-36xw-fx78-c5r4"
reason = "https://osv.dev/GHSA-36xw-fx78-c5r4"

[[IgnoredVulns]]
id = "GHSA-742w-89gc-8m9c"
reason = "https://osv.dev/GHSA-742w-89gc-8m9c"

[[IgnoredVulns]]
id = "GHSA-c72p-9xmj-rx3w"
reason = "https://osv.dev/GHSA-c72p-9xmj-rx3w"

[[IgnoredVulns]]
id = "GHSA-c2h3-6mxw-7mvq"
reason = "https://osv.dev/GHSA-c2h3-6mxw-7mvq"

[[IgnoredVulns]]
id = "GHSA-5j5w-g665-5m35"
reason = "https://osv.dev/GHSA-5j5w-g665-5m35"

[[IgnoredVulns]]
id = "GHSA-crp2-qrr5-8pq7"
reason = "https://osv.dev/GHSA-crp2-qrr5-8pq7"

[[IgnoredVulns]]
id = "GHSA-5ffw-gxpp-mxpf"
reason = "https://osv.dev/GHSA-5ffw-gxpp-mxpf"

[[IgnoredVulns]]
id = "GHSA-2qjp-425j-52j9"
reason = "https://osv.dev/GHSA-2qjp-425j-52j9"

[[IgnoredVulns]]
id = "GHSA-36xw-fx78-c5r4"
reason = "https://osv.dev/GHSA-36xw-fx78-c5r4"

[[IgnoredVulns]]
id = "GHSA-742w-89gc-8m9c"
reason = "https://osv.dev/GHSA-742w-89gc-8m9c"

[[IgnoredVulns]]
id = "GHSA-c72p-9xmj-rx3w"
reason = "https://osv.dev/GHSA-c72p-9xmj-rx3w"

[[IgnoredVulns]]
id = "GHSA-c2h3-6mxw-7mvq"
reason = "https://osv.dev/GHSA-c2h3-6mxw-7mvq"

[[IgnoredVulns]]
id = "GHSA-5j5w-g665-5m35"
reason = "https://osv.dev/GHSA-5j5w-g665-5m35"

[[IgnoredVulns]]
id = "GHSA-crp2-qrr5-8pq7"
reason = "https://osv.dev/GHSA-crp2-qrr5-8pq7"

[[IgnoredVulns]]
id = "GHSA-5ffw-gxpp-mxpf"
reason = "https://osv.dev/GHSA-5ffw-gxpp-mxpf"

[[IgnoredVulns]]
id = "GHSA-2qjp-425j-52j9"
reason = "https://osv.dev/GHSA-2qjp-425j-52j9"

[[IgnoredVulns]]
id = "GHSA-2qjp-425j-52j9"
reason = "https://osv.dev/GHSA-2qjp-425j-52j9"

[[IgnoredVulns]]
id = "GHSA-r48q-9g5r-8q2h"
reason = "https://osv.dev/GHSA-r48q-9g5r-8q2h"

[[IgnoredVulns]]
id = "GO-2022-0619"
reason = "https://osv.dev/GO-2022-0619"

[[IgnoredVulns]]
id = "GHSA-q3j5-32m5-58c2"
reason = "https://osv.dev/GHSA-q3j5-32m5-58c2"

[[IgnoredVulns]]
id = "GO-2021-0070"
reason = "https://osv.dev/GO-2021-0070"

[[IgnoredVulns]]
id = "GHSA-gp4j-w3vj-7299"
reason = "https://osv.dev/GHSA-gp4j-w3vj-7299"

[[IgnoredVulns]]
id = "GO-2021-0085"
reason = "https://osv.dev/GO-2021-0085"

[[IgnoredVulns]]
id = "GHSA-fgv8-vj5c-2ppq"
reason = "https://osv.dev/GHSA-fgv8-vj5c-2ppq"

[[IgnoredVulns]]
id = "GO-2021-0087"
reason = "https://osv.dev/GO-2021-0087"

[[IgnoredVulns]]
id = "GHSA-g54h-m393-cpwq"
reason = "https://osv.dev/GHSA-g54h-m393-cpwq"

[[IgnoredVulns]]
id = "GHSA-c3xm-pvg7-gh7r"
reason = "https://osv.dev/GHSA-c3xm-pvg7-gh7r"

[[IgnoredVulns]]
id = "GHSA-v95c-p5hm-xq8f"
reason = "https://osv.dev/GHSA-v95c-p5hm-xq8f"

[[IgnoredVulns]]
id = "GHSA-f3fp-gc8g-vw66"
reason = "https://osv.dev/GHSA-f3fp-gc8g-vw66"

[[IgnoredVulns]]
id = "GO-2022-0236"
reason = "https://osv.dev/GO-2022-0236"

[[IgnoredVulns]]
id = "GO-2021-0238"
reason = "https://osv.dev/GO-2021-0238"

[[IgnoredVulns]]
id = "GO-2022-0288"
reason = "https://osv.dev/GO-2022-0288"

[[IgnoredVulns]]
id = "GO-2022-0969"
reason = "https://osv.dev/GO-2022-0969"

[[IgnoredVulns]]
id = "GO-2022-1144"
reason = "https://osv.dev/GO-2022-1144"

[[IgnoredVulns]]
id = "GO-2022-0969"
reason = "https://osv.dev/GO-2022-0969"

[[IgnoredVulns]]
id = "GO-2023-1495"
reason = "https://osv.dev/GO-2023-1495"

[[IgnoredVulns]]
id = "GO-2022-1144"
reason = "https://osv.dev/GO-2022-1144"

[[IgnoredVulns]]
id = "GO-2022-0969"
reason = "https://osv.dev/GO-2022-0969"

[[IgnoredVulns]]
id = "GO-2023-1495"
reason = "https://osv.dev/GO-2023-1495"

[[IgnoredVulns]]
id = "GO-2022-1144"
reason = "https://osv.dev/GO-2022-1144"

[[IgnoredVulns]]
id = "GO-2022-0969"
reason = "https://osv.dev/GO-2022-0969"

[[IgnoredVulns]]
id = "GO-2023-1495"
reason = "https://osv.dev/GO-2023-1495"

[[IgnoredVulns]]
id = "GO-2022-1144"
reason = "https://osv.dev/GO-2022-1144"

[[IgnoredVulns]]
id = "GO-2023-1495"
reason = "https://osv.dev/GO-2023-1495"

[[IgnoredVulns]]
id = "GO-2022-1144"
reason = "https://osv.dev/GO-2022-1144"

[[IgnoredVulns]]
id = "GO-2022-0493"
reason = "https://osv.dev/GO-2022-0493"

[[IgnoredVulns]]
id = "GO-2022-1059"
reason = "https://osv.dev/GO-2022-1059"

[[IgnoredVulns]]
id = "GO-2022-1059"
reason = "https://osv.dev/GO-2022-1059"
